version: '3.9'
services:
  # PHP-FPM Service
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mounts the local 'app' directory to the container's Nginx root
      - ./app:/var/www/html
    depends_on:
      # Depends on the MySQL database service
      - mysql

  # NGINX Service
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      # Mountlocal 'app' directory to the Nginx root
      - ./app:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - php-fpm # Depends on the PHP-FPM service
      - mysql # Depends on the MySQL database service

  # MySQL Database Service
  mysql:
    image: mysql:latest
    volumes:
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: usmiledee_gallery_db
      MYSQL_USER: usmile
      MYSQL_PASSWORD: D3v0t3D%$
    ports:
      # Maps port 3306 on the host to port 3306 on the MySQL container
      - "3306:3306"

  # PHPMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      # Links the PHPMyAdmin service to the MySQL database service
      - mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      # Use MySQL root password for PHPMyAdmin
      MYSQL_ROOT_PASSWORD: secret
